[workspace]
authors = ["LnOS Development Team <rcocker87@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "lnos"
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.6.0.dev2025081405,<26"
mojo-compiler = ">=25.6.0.dev2025081405,<26"
max = ">=25.6.0.dev2025081405,<26"
python = ">=3.13.5,<3.14"
